version: '2.4'

services:
  elpaas:
    build: .
    image: elpaas:latest
    restart: on-failure
    ports:
     - "8282:8000"    
    environment:
      DJANGO__bool__DEBUG: ${DEBUG}
      DJANGO__ALLOWED_HOSTS: "*"
      DJANGO__EMAIL_HOST: ${EMAIL_HOST}
      DJANGO__EMAIL_HOST_USER: ${EMAIL_USER}
      DJANGO__EMAIL_HOST_PASSWORD: ${EMAIL_PASS}