name: env
channels:
  - defaults
dependencies:
  - python=3.7 
  - pandas
  - scipy
  - numpy
  - requests
  - django
  - pip:
      - subprocess
      - pm4py
      - time
      - sqlite3
      - anytree
      - datetime